"""
Test case configurations for cluster validation.

This module contains all test case configurations organized by category.
"""

SMALL_TEST_CASES = [
    {
        "name": "clear",
        "n_samples": 24,
        "n_features": 12,
        "n_clusters": 3,
        "cluster_std": 0.4,
        "seed": 0,
    },
    {
        "name": "moderate",
        "n_samples": 30,
        "n_features": 16,
        "n_clusters": 3,
        "cluster_std": 1.0,
        "seed": 1,
    },
    {
        "name": "noisy",
        "n_samples": 30,
        "n_features": 16,
        "n_clusters": 3,
        "cluster_std": 1.6,
        "seed": 2,
    },
]

# Modular test case configuration
DEFAULT_TEST_CASES_CONFIG = {
    "gaussian_clear": [
        {
            "n_samples": 30,
            "n_features": 30,
            "n_clusters": 3,
            "cluster_std": 0.5,
            "seed": 100,
        },
        {
            "n_samples": 40,
            "n_features": 40,
            "n_clusters": 4,
            "cluster_std": 0.8,
            "seed": 101,
        },
        {
            "n_samples": 50,
            "n_features": 50,
            "n_clusters": 5,
            "cluster_std": 1.0,
            "seed": 102,
        },
    ],
    "gaussian_mixed": [
        {
            "n_samples": 35,
            "n_features": 35,
            "n_clusters": 3,
            "cluster_std": 1.2,
            "seed": 103,
        },
        {
            "n_samples": 45,
            "n_features": 45,
            "n_clusters": 4,
            "cluster_std": 1.5,
            "seed": 104,
        },
        {
            "n_samples": 55,
            "n_features": 55,
            "n_clusters": 5,
            "cluster_std": 1.8,
            "seed": 105,
        },
        {
            "n_samples": 25,
            "n_features": 25,
            "n_clusters": 2,
            "cluster_std": 0.7,
            "seed": 106,
        },
        {
            "n_samples": 65,
            "n_features": 65,
            "n_clusters": 6,
            "cluster_std": 2.0,
            "seed": 107,
        },
    ],
    "gaussian_extreme_noise": [
        {
            "n_samples": 30,
            "n_features": 30,
            "n_clusters": 3,
            "cluster_std": 5.0,
            "seed": 42,
        },
        {
            "n_samples": 40,
            "n_features": 20000,
            "n_clusters": 4,
            "cluster_std": 7.5,
            "seed": 43,
        },
        {
            "n_samples": 300,
            "n_features": 2000,
            "n_clusters": 30,
            "cluster_std": 2,
            "seed": 44,
        },
    ],
    # Renamed from "binary_balanced_low_entropy" to "binary_balanced_low_noise"
    # entropy_param controls NOISE level (cluster separation), NOT feature variance
    "binary_balanced_low_noise": [
        {
            "name": "binary_balanced_low_noise",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 72,
            "n_clusters": 4,
            "entropy_param": 0.25,  # 25% noise (low noise = good separation)
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_noise",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 40,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_noise",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 80,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_noise",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 120,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_noise",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 140,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_noise",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 160,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_noise",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 180,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_noise",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 220,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_noise",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 1200,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_noise",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 120,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
    ],
    # NEW: Test cases with actual low-variance features (θ near 0 or 1)
    # These test the variance-weighted df reduction
    "binary_sparse_features": [
        {
            "name": "sparse_features_72x72",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 72,
            "n_clusters": 4,
            "entropy_param": 0.1,  # Low noise
            "balanced_clusters": True,
            "feature_sparsity": 0.05,  # Features have θ ≈ 0.05 or 0.95
            "seed": 500,
        },
        {
            "name": "sparse_features_100x100",
            "generator": "binary",
            "n_rows": 100,
            "n_cols": 100,
            "n_clusters": 4,
            "entropy_param": 0.1,
            "balanced_clusters": True,
            "feature_sparsity": 0.05,
            "seed": 501,
        },
        {
            "name": "sparse_features_100x500",
            "generator": "binary",
            "n_rows": 100,
            "n_cols": 500,
            "n_clusters": 4,
            "entropy_param": 0.1,
            "balanced_clusters": True,
            "feature_sparsity": 0.05,  # Should reduce effective df from 500 to ~90
            "seed": 502,
        },
        {
            "name": "sparse_features_moderate",
            "generator": "binary",
            "n_rows": 100,
            "n_cols": 200,
            "n_clusters": 4,
            "entropy_param": 0.15,
            "balanced_clusters": True,
            "feature_sparsity": 0.1,  # Features have θ ≈ 0.1 or 0.9
            "seed": 503,
        },
        {
            "name": "sparse_features_extreme",
            "generator": "binary",
            "n_rows": 100,
            "n_cols": 1000,
            "n_clusters": 4,
            "entropy_param": 0.1,
            "balanced_clusters": True,
            "feature_sparsity": 0.02,  # Very sparse: θ ≈ 0.02 or 0.98
            "seed": 504,
        },
    ],
    # Renamed from "binary_unbalanced_high_entropy" to "binary_unbalanced_high_noise"
    "binary_unbalanced_high_noise": [
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 36,
            "n_clusters": 4,
            "entropy_param": 0.45,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 36,
            "n_clusters": 4,
            "entropy_param": 0.12,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 300,
            "n_clusters": 4,
            "entropy_param": 0.00,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 300,
            "n_clusters": 4,
            "entropy_param": 0.01,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 300,
            "n_clusters": 4,
            "entropy_param": 0.02,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.12,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.17,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.22,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.27,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.28,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.29,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.30,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.31,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.32,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.33,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.34,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.35,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 180,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.35,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 360,
            "n_cols": 3000,
            "n_clusters": 8,
            "entropy_param": 0.05,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 480,
            "n_cols": 3000,
            "n_clusters": 8,
            "entropy_param": 0.10,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 480,
            "n_cols": 3000,
            "n_clusters": 12,
            "entropy_param": 0.10,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 480,
            "n_cols": 3000,
            "n_clusters": 12,
            "entropy_param": 0.15,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 480,
            "n_cols": 3000,
            "n_clusters": 12,
            "entropy_param": 0.20,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 480,
            "n_cols": 3000,
            "n_clusters": 12,
            "entropy_param": 0.25,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 480,
            "n_cols": 3000,
            "n_clusters": 8,
            "entropy_param": 0.05,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 360,
            "n_cols": 3000,
            "n_clusters": 8,
            "entropy_param": 0.10,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 360,
            "n_cols": 3000,
            "n_clusters": 12,
            "entropy_param": 0.10,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 360,
            "n_cols": 3000,
            "n_clusters": 12,
            "entropy_param": 0.15,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 360,
            "n_cols": 3000,
            "n_clusters": 12,
            "entropy_param": 0.20,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_noise",
            "generator": "binary",
            "n_rows": 360,
            "n_cols": 3000,
            "n_clusters": 12,
            "entropy_param": 0.25,
            "balanced_clusters": False,
            "seed": 2024,
        },
    ],
    # =========================================================================
    # IMPROVED TEST CASES - Well-designed with verified cluster structure
    # All cases have signal ratio > 1.5 (detectable cluster structure)
    # =========================================================================
    "improved_gaussian": [
        # Clear separation (should get 100% correct)
        {
            "name": "gauss_clear_small",
            "n_samples": 30,
            "n_features": 20,
            "n_clusters": 3,
            "cluster_std": 0.5,
            "seed": 100,
        },
        {
            "name": "gauss_clear_medium",
            "n_samples": 60,
            "n_features": 40,
            "n_clusters": 4,
            "cluster_std": 0.6,
            "seed": 101,
        },
        {
            "name": "gauss_clear_large",
            "n_samples": 100,
            "n_features": 80,
            "n_clusters": 5,
            "cluster_std": 0.7,
            "seed": 102,
        },
        # Moderate overlap (80-95% ARI expected)
        {
            "name": "gauss_moderate_3c",
            "n_samples": 45,
            "n_features": 30,
            "n_clusters": 3,
            "cluster_std": 1.2,
            "seed": 200,
        },
        {
            "name": "gauss_moderate_5c",
            "n_samples": 75,
            "n_features": 50,
            "n_clusters": 5,
            "cluster_std": 1.5,
            "seed": 201,
        },
        # Challenging (50-80% ARI expected)
        {
            "name": "gauss_noisy_3c",
            "n_samples": 60,
            "n_features": 40,
            "n_clusters": 3,
            "cluster_std": 2.5,
            "seed": 300,
        },
        {
            "name": "gauss_noisy_many",
            "n_samples": 120,
            "n_features": 80,
            "n_clusters": 8,
            "cluster_std": 2.0,
            "seed": 301,
        },
    ],
    "sbm_graphs": [
        {
            "name": "sbm_clear_small",
            "generator": "sbm",
            "sizes": [30, 30],
            "p_intra": 0.12,
            "p_inter": 0.005,
            "seed": 123,
        },
        {
            "name": "sbm_moderate",
            "generator": "sbm",
            "sizes": [50, 40, 30],
            "p_intra": 0.08,
            "p_inter": 0.02,
            "seed": 124,
        },
        {
            "name": "sbm_hard",
            "generator": "sbm",
            "sizes": [40, 40, 40],
            "p_intra": 0.05,
            "p_inter": 0.04,
            "seed": 125,
        },
    ],
    "sbm_graphs": [
        {
            "name": "sbm_clear_small",
            "generator": "sbm",
            "sizes": [30, 30],
            "p_intra": 0.12,
            "p_inter": 0.005,
            "seed": 123,
        },
        {
            "name": "sbm_moderate",
            "generator": "sbm",
            "sizes": [50, 40, 30],
            "p_intra": 0.08,
            "p_inter": 0.02,
            "seed": 124,
        },
        {
            "name": "sbm_hard",
            "generator": "sbm",
            "sizes": [40, 40, 40],
            "p_intra": 0.05,
            "p_inter": 0.04,
            "seed": 125,
        },
    ],
    "improved_binary_perfect": [
        # TIER 1: Perfect separation (entropy=0, should get 100% ARI)
        {
            "name": "binary_perfect_2c",
            "generator": "binary",
            "n_rows": 40,
            "n_cols": 50,
            "n_clusters": 2,
            "entropy_param": 0.00,
            "balanced_clusters": True,
            "seed": 1000,
        },
        {
            "name": "binary_perfect_4c",
            "generator": "binary",
            "n_rows": 80,
            "n_cols": 100,
            "n_clusters": 4,
            "entropy_param": 0.00,
            "balanced_clusters": True,
            "seed": 1001,
        },
        {
            "name": "binary_perfect_8c",
            "generator": "binary",
            "n_rows": 160,
            "n_cols": 200,
            "n_clusters": 8,
            "entropy_param": 0.00,
            "balanced_clusters": True,
            "seed": 1002,
        },
    ],
    "improved_binary_low_noise": [
        # TIER 2: Low noise (entropy=0.05-0.10, should get 95%+ ARI)
        {
            "name": "binary_low_noise_2c",
            "generator": "binary",
            "n_rows": 40,
            "n_cols": 50,
            "n_clusters": 2,
            "entropy_param": 0.05,
            "balanced_clusters": True,
            "seed": 2000,
        },
        {
            "name": "binary_low_noise_4c",
            "generator": "binary",
            "n_rows": 80,
            "n_cols": 100,
            "n_clusters": 4,
            "entropy_param": 0.05,
            "balanced_clusters": True,
            "seed": 2001,
        },
        {
            "name": "binary_low_noise_8c",
            "generator": "binary",
            "n_rows": 160,
            "n_cols": 200,
            "n_clusters": 8,
            "entropy_param": 0.10,
            "balanced_clusters": True,
            "seed": 2002,
        },
        {
            "name": "binary_low_noise_12c",
            "generator": "binary",
            "n_rows": 240,
            "n_cols": 300,
            "n_clusters": 12,
            "entropy_param": 0.10,
            "balanced_clusters": True,
            "seed": 2003,
        },
    ],
    "improved_binary_moderate": [
        # TIER 3: Moderate noise (entropy=0.12-0.15, should get 80-95% ARI)
        {
            "name": "binary_moderate_4c",
            "generator": "binary",
            "n_rows": 80,
            "n_cols": 100,
            "n_clusters": 4,
            "entropy_param": 0.12,
            "balanced_clusters": True,
            "seed": 3000,
        },
        {
            "name": "binary_moderate_6c",
            "generator": "binary",
            "n_rows": 120,
            "n_cols": 150,
            "n_clusters": 6,
            "entropy_param": 0.15,
            "balanced_clusters": True,
            "seed": 3001,
        },
        {
            "name": "binary_moderate_8c",
            "generator": "binary",
            "n_rows": 200,
            "n_cols": 250,
            "n_clusters": 8,
            "entropy_param": 0.12,
            "balanced_clusters": True,
            "seed": 3002,
        },
        {
            "name": "binary_moderate_many_feat",
            "generator": "binary",
            "n_rows": 100,
            "n_cols": 1000,
            "n_clusters": 4,
            "entropy_param": 0.15,
            "balanced_clusters": True,
            "seed": 3003,
        },
    ],
    "improved_binary_hard": [
        # TIER 4: Challenging (entropy=0.15-0.20)
        {
            "name": "binary_hard_4c",
            "generator": "binary",
            "n_rows": 100,
            "n_cols": 200,
            "n_clusters": 4,
            "entropy_param": 0.20,
            "balanced_clusters": True,
            "seed": 4000,
        },
        {
            "name": "binary_hard_8c",
            "generator": "binary",
            "n_rows": 280,
            "n_cols": 400,
            "n_clusters": 8,
            "entropy_param": 0.15,
            "balanced_clusters": True,
            "seed": 4001,
        },
    ],
    "improved_binary_unbalanced": [
        # Unbalanced clusters
        {
            "name": "binary_unbalanced_low",
            "generator": "binary",
            "n_rows": 100,
            "n_cols": 150,
            "n_clusters": 4,
            "entropy_param": 0.10,
            "balanced_clusters": False,
            "seed": 5000,
        },
        {
            "name": "binary_unbalanced_med",
            "generator": "binary",
            "n_rows": 150,
            "n_cols": 200,
            "n_clusters": 6,
            "entropy_param": 0.12,
            "balanced_clusters": False,
            "seed": 5001,
        },
        {
            "name": "binary_unbalanced_hard",
            "generator": "binary",
            "n_rows": 200,
            "n_cols": 300,
            "n_clusters": 8,
            "entropy_param": 0.15,
            "balanced_clusters": False,
            "seed": 5002,
        },
    ],
    "improved_binary_sparse": [
        # Sparse features (low variance, tests df weighting)
        {
            "name": "binary_sparse_low",
            "generator": "binary",
            "n_rows": 80,
            "n_cols": 100,
            "n_clusters": 4,
            "entropy_param": 0.10,
            "feature_sparsity": 0.05,
            "balanced_clusters": True,
            "seed": 6000,
        },
        {
            "name": "binary_sparse_med",
            "generator": "binary",
            "n_rows": 100,
            "n_cols": 200,
            "n_clusters": 4,
            "entropy_param": 0.12,
            "feature_sparsity": 0.10,
            "balanced_clusters": True,
            "seed": 6001,
        },
        {
            "name": "binary_sparse_high",
            "generator": "binary",
            "n_rows": 100,
            "n_cols": 500,
            "n_clusters": 4,
            "entropy_param": 0.10,
            "feature_sparsity": 0.05,
            "balanced_clusters": True,
            "seed": 6002,
        },
    ],
    "improved_binary_edge_cases": [
        # Edge cases
        {
            "name": "binary_2clusters",
            "generator": "binary",
            "n_rows": 50,
            "n_cols": 60,
            "n_clusters": 2,
            "entropy_param": 0.10,
            "balanced_clusters": True,
            "seed": 7000,
        },
        {
            "name": "binary_small_samples",
            "generator": "binary",
            "n_rows": 40,
            "n_cols": 80,
            "n_clusters": 4,
            "entropy_param": 0.08,
            "balanced_clusters": True,
            "seed": 7001,
        },
        {
            "name": "binary_many_features",
            "generator": "binary",
            "n_rows": 100,
            "n_cols": 2000,
            "n_clusters": 4,
            "entropy_param": 0.10,
            "balanced_clusters": True,
            "seed": 7002,
        },
        {
            "name": "binary_many_clusters",
            "generator": "binary",
            "n_rows": 300,
            "n_cols": 400,
            "n_clusters": 15,
            "entropy_param": 0.10,
            "balanced_clusters": True,
            "seed": 7003,
        },
    ],
    # =========================================================================
    # OVERLAPPING CLUSTERS - Clusters that lie on top of each other
    # These test the algorithm's behavior when ground truth clusters are
    # statistically indistinguishable. Algorithm SHOULD find fewer clusters.
    # HIGH SAMPLE SIZES with varied feature dimensions
    # =========================================================================
    "overlapping_binary_heavy": [
        # Heavy overlap (entropy 0.40-0.48) - nearly random, almost no signal
        {
            "name": "overlap_heavy_4c_small_feat",
            "generator": "binary",
            "n_rows": 500,
            "n_cols": 50,
            "n_clusters": 4,
            "entropy_param": 0.40,
            "balanced_clusters": True,
            "seed": 8000,
        },
        {
            "name": "overlap_heavy_4c_med_feat",
            "generator": "binary",
            "n_rows": 500,
            "n_cols": 200,
            "n_clusters": 4,
            "entropy_param": 0.40,
            "balanced_clusters": True,
            "seed": 8001,
        },
        {
            "name": "overlap_heavy_8c_large_feat",
            "generator": "binary",
            "n_rows": 800,
            "n_cols": 500,
            "n_clusters": 8,
            "entropy_param": 0.40,
            "balanced_clusters": True,
            "seed": 8002,
        },
        {
            "name": "overlap_extreme_4c",
            "generator": "binary",
            "n_rows": 600,
            "n_cols": 150,
            "n_clusters": 4,
            "entropy_param": 0.48,
            "balanced_clusters": True,
            "seed": 8003,
        },
        {
            "name": "overlap_extreme_6c_highd",
            "generator": "binary",
            "n_rows": 600,
            "n_cols": 1000,
            "n_clusters": 6,
            "entropy_param": 0.45,
            "balanced_clusters": True,
            "seed": 8004,
        },
    ],
    "overlapping_binary_moderate": [
        # Moderate overlap (entropy 0.28-0.35) - some structure, many merges expected
        {
            "name": "overlap_mod_4c_small",
            "generator": "binary",
            "n_rows": 400,
            "n_cols": 80,
            "n_clusters": 4,
            "entropy_param": 0.30,
            "balanced_clusters": True,
            "seed": 8100,
        },
        {
            "name": "overlap_mod_6c_med",
            "generator": "binary",
            "n_rows": 600,
            "n_cols": 250,
            "n_clusters": 6,
            "entropy_param": 0.30,
            "balanced_clusters": True,
            "seed": 8101,
        },
        {
            "name": "overlap_mod_8c_large",
            "generator": "binary",
            "n_rows": 800,
            "n_cols": 400,
            "n_clusters": 8,
            "entropy_param": 0.28,
            "balanced_clusters": True,
            "seed": 8102,
        },
        {
            "name": "overlap_mod_10c_highd",
            "generator": "binary",
            "n_rows": 1000,
            "n_cols": 800,
            "n_clusters": 10,
            "entropy_param": 0.32,
            "balanced_clusters": True,
            "seed": 8103,
        },
    ],
    "overlapping_binary_partial": [
        # Partial overlap (entropy 0.22-0.26) - some clusters merge, others separate
        {
            "name": "overlap_part_4c_small",
            "generator": "binary",
            "n_rows": 400,
            "n_cols": 60,
            "n_clusters": 4,
            "entropy_param": 0.24,
            "balanced_clusters": True,
            "seed": 8200,
        },
        {
            "name": "overlap_part_6c_med",
            "generator": "binary",
            "n_rows": 600,
            "n_cols": 200,
            "n_clusters": 6,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 8201,
        },
        {
            "name": "overlap_part_8c_large",
            "generator": "binary",
            "n_rows": 800,
            "n_cols": 350,
            "n_clusters": 8,
            "entropy_param": 0.22,
            "balanced_clusters": True,
            "seed": 8202,
        },
        {
            "name": "overlap_part_10c_highd",
            "generator": "binary",
            "n_rows": 1000,
            "n_cols": 600,
            "n_clusters": 10,
            "entropy_param": 0.23,
            "balanced_clusters": True,
            "seed": 8203,
        },
    ],
    "overlapping_binary_highd": [
        # High-dimensional overlap - tests overlap in high feature space
        {
            "name": "overlap_hd_4c_1k",
            "generator": "binary",
            "n_rows": 500,
            "n_cols": 1000,
            "n_clusters": 4,
            "entropy_param": 0.35,
            "balanced_clusters": True,
            "seed": 8300,
        },
        {
            "name": "overlap_hd_6c_2k",
            "generator": "binary",
            "n_rows": 600,
            "n_cols": 2000,
            "n_clusters": 6,
            "entropy_param": 0.33,
            "balanced_clusters": True,
            "seed": 8301,
        },
        {
            "name": "overlap_hd_8c_3k",
            "generator": "binary",
            "n_rows": 800,
            "n_cols": 3000,
            "n_clusters": 8,
            "entropy_param": 0.30,
            "balanced_clusters": True,
            "seed": 8302,
        },
        {
            "name": "overlap_hd_10c_5k",
            "generator": "binary",
            "n_rows": 1000,
            "n_cols": 5000,
            "n_clusters": 10,
            "entropy_param": 0.28,
            "balanced_clusters": True,
            "seed": 8303,
        },
    ],
    "overlapping_binary_unbalanced": [
        # Unbalanced overlapping - small clusters get lost in overlap
        {
            "name": "overlap_unbal_4c_small",
            "generator": "binary",
            "n_rows": 400,
            "n_cols": 100,
            "n_clusters": 4,
            "entropy_param": 0.35,
            "balanced_clusters": False,
            "seed": 8400,
        },
        {
            "name": "overlap_unbal_6c_med",
            "generator": "binary",
            "n_rows": 600,
            "n_cols": 300,
            "n_clusters": 6,
            "entropy_param": 0.30,
            "balanced_clusters": False,
            "seed": 8401,
        },
        {
            "name": "overlap_unbal_8c_large",
            "generator": "binary",
            "n_rows": 800,
            "n_cols": 500,
            "n_clusters": 8,
            "entropy_param": 0.32,
            "balanced_clusters": False,
            "seed": 8402,
        },
        {
            "name": "overlap_unbal_10c_highd",
            "generator": "binary",
            "n_rows": 1000,
            "n_cols": 1000,
            "n_clusters": 10,
            "entropy_param": 0.28,
            "balanced_clusters": False,
            "seed": 8403,
        },
    ],
    # =========================================================================
    # GAUSSIAN OVERLAPPING - Continuous clusters with high std overlap
    # HIGH SAMPLE SIZES with varied feature dimensions
    # =========================================================================
    "overlapping_gaussian": [
        # High cluster_std means Gaussian blobs overlap significantly
        {
            "name": "gauss_overlap_3c_small",
            "n_samples": 300,
            "n_features": 30,
            "n_clusters": 3,
            "cluster_std": 3.5,
            "seed": 9000,
        },
        {
            "name": "gauss_overlap_4c_med",
            "n_samples": 400,
            "n_features": 80,
            "n_clusters": 4,
            "cluster_std": 4.0,
            "seed": 9001,
        },
        {
            "name": "gauss_overlap_6c_large",
            "n_samples": 600,
            "n_features": 150,
            "n_clusters": 6,
            "cluster_std": 3.5,
            "seed": 9002,
        },
        {
            "name": "gauss_overlap_8c_highd",
            "n_samples": 800,
            "n_features": 300,
            "n_clusters": 8,
            "cluster_std": 3.5,
            "seed": 9003,
        },
        # Extreme overlap - essentially uniform distribution
        {
            "name": "gauss_overlap_extreme_4c",
            "n_samples": 500,
            "n_features": 100,
            "n_clusters": 4,
            "cluster_std": 6.0,
            "seed": 9100,
        },
        {
            "name": "gauss_overlap_extreme_6c",
            "n_samples": 600,
            "n_features": 200,
            "n_clusters": 6,
            "cluster_std": 5.5,
            "seed": 9101,
        },
        {
            "name": "gauss_overlap_many_10c",
            "n_samples": 1000,
            "n_features": 150,
            "n_clusters": 10,
            "cluster_std": 4.0,
            "seed": 9102,
        },
        {
            "name": "gauss_overlap_dense_8c",
            "n_samples": 800,
            "n_features": 50,
            "n_clusters": 8,
            "cluster_std": 3.0,
            "seed": 9103,
        },
    ],
    # =========================================================================
    # CATEGORICAL (MULTINOMIAL) DISTRIBUTIONS
    # Each feature has K categories (not just binary 0/1)
    # Tests the categorical distribution support in the pipeline
    # =========================================================================
    "categorical_clear": [
        # Clear separation with 3 categories per feature
        {
            "name": "cat_clear_3cat_4c",
            "generator": "categorical",
            "n_rows": 100,
            "n_cols": 50,
            "n_clusters": 4,
            "n_categories": 3,
            "entropy_param": 0.05,  # Low noise
            "balanced_clusters": True,
            "seed": 10000,
        },
        {
            "name": "cat_clear_4cat_4c",
            "generator": "categorical",
            "n_rows": 100,
            "n_cols": 50,
            "n_clusters": 4,
            "n_categories": 4,
            "entropy_param": 0.05,
            "balanced_clusters": True,
            "seed": 10001,
        },
        {
            "name": "cat_clear_5cat_6c",
            "generator": "categorical",
            "n_rows": 150,
            "n_cols": 80,
            "n_clusters": 6,
            "n_categories": 5,
            "entropy_param": 0.08,
            "balanced_clusters": True,
            "seed": 10002,
        },
    ],
    "categorical_moderate": [
        # Moderate noise with various category counts
        {
            "name": "cat_mod_3cat_4c",
            "generator": "categorical",
            "n_rows": 120,
            "n_cols": 60,
            "n_clusters": 4,
            "n_categories": 3,
            "entropy_param": 0.15,
            "balanced_clusters": True,
            "seed": 10100,
        },
        {
            "name": "cat_mod_4cat_6c",
            "generator": "categorical",
            "n_rows": 180,
            "n_cols": 100,
            "n_clusters": 6,
            "n_categories": 4,
            "entropy_param": 0.18,
            "balanced_clusters": True,
            "seed": 10101,
        },
        {
            "name": "cat_mod_6cat_8c",
            "generator": "categorical",
            "n_rows": 240,
            "n_cols": 120,
            "n_clusters": 8,
            "n_categories": 6,
            "entropy_param": 0.15,
            "balanced_clusters": True,
            "seed": 10102,
        },
    ],
    "categorical_high_cardinality": [
        # Many categories per feature (like DNA codons, amino acids)
        {
            "name": "cat_highcard_10cat_4c",
            "generator": "categorical",
            "n_rows": 200,
            "n_cols": 50,
            "n_clusters": 4,
            "n_categories": 10,
            "entropy_param": 0.10,
            "balanced_clusters": True,
            "seed": 10200,
        },
        {
            "name": "cat_highcard_20cat_4c",
            "generator": "categorical",
            "n_rows": 200,
            "n_cols": 40,
            "n_clusters": 4,
            "n_categories": 20,  # Like amino acids
            "entropy_param": 0.12,
            "balanced_clusters": True,
            "seed": 10201,
        },
        {
            "name": "cat_highcard_64cat_4c",
            "generator": "categorical",
            "n_rows": 300,
            "n_cols": 30,
            "n_clusters": 4,
            "n_categories": 64,  # Like DNA codons
            "entropy_param": 0.10,
            "balanced_clusters": True,
            "seed": 10202,
        },
    ],
    "categorical_unbalanced": [
        # Unbalanced cluster sizes
        {
            "name": "cat_unbal_3cat_4c",
            "generator": "categorical",
            "n_rows": 150,
            "n_cols": 60,
            "n_clusters": 4,
            "n_categories": 3,
            "entropy_param": 0.12,
            "balanced_clusters": False,
            "seed": 10300,
        },
        {
            "name": "cat_unbal_5cat_6c",
            "generator": "categorical",
            "n_rows": 200,
            "n_cols": 80,
            "n_clusters": 6,
            "n_categories": 5,
            "entropy_param": 0.15,
            "balanced_clusters": False,
            "seed": 10301,
        },
    ],
    "categorical_overlapping": [
        # Overlapping categorical clusters (high noise)
        {
            "name": "cat_overlap_3cat_4c",
            "generator": "categorical",
            "n_rows": 400,
            "n_cols": 100,
            "n_clusters": 4,
            "n_categories": 3,
            "entropy_param": 0.35,
            "balanced_clusters": True,
            "seed": 10400,
        },
        {
            "name": "cat_overlap_5cat_6c",
            "generator": "categorical",
            "n_rows": 600,
            "n_cols": 150,
            "n_clusters": 6,
            "n_categories": 5,
            "entropy_param": 0.40,
            "balanced_clusters": True,
            "seed": 10401,
        },
        {
            "name": "cat_overlap_extreme_4c",
            "generator": "categorical",
            "n_rows": 500,
            "n_cols": 80,
            "n_clusters": 4,
            "n_categories": 4,
            "entropy_param": 0.45,
            "balanced_clusters": True,
            "seed": 10402,
        },
    ],
    "categorical_sparse": [
        # Sparse categorical (most probability mass on one category)
        {
            "name": "cat_sparse_4cat_4c",
            "generator": "categorical",
            "n_rows": 120,
            "n_cols": 100,
            "n_clusters": 4,
            "n_categories": 4,
            "entropy_param": 0.08,
            "category_sparsity": 0.85,  # 85% mass on dominant category
            "balanced_clusters": True,
            "seed": 10500,
        },
        {
            "name": "cat_sparse_10cat_4c",
            "generator": "categorical",
            "n_rows": 150,
            "n_cols": 80,
            "n_clusters": 4,
            "n_categories": 10,
            "entropy_param": 0.10,
            "category_sparsity": 0.90,  # 90% mass on dominant category
            "balanced_clusters": True,
            "seed": 10501,
        },
    ],
    "categorical_high_dimensional": [
        # High-dimensional categorical data
        {
            "name": "cat_highd_3cat_500feat",
            "generator": "categorical",
            "n_rows": 200,
            "n_cols": 500,
            "n_clusters": 4,
            "n_categories": 3,
            "entropy_param": 0.12,
            "balanced_clusters": True,
            "seed": 10600,
        },
        {
            "name": "cat_highd_4cat_1000feat",
            "generator": "categorical",
            "n_rows": 300,
            "n_cols": 1000,
            "n_clusters": 6,
            "n_categories": 4,
            "entropy_param": 0.15,
            "balanced_clusters": True,
            "seed": 10601,
        },
        {
            "name": "cat_highd_5cat_2000feat",
            "generator": "categorical",
            "n_rows": 400,
            "n_cols": 2000,
            "n_clusters": 8,
            "n_categories": 5,
            "entropy_param": 0.10,
            "balanced_clusters": True,
            "seed": 10602,
        },
    ],
    # =========================================================================
    # PHYLOGENETIC SIMULATIONS
    # Simulates trait evolution along a phylogenetic tree
    # Closely related taxa have more similar distributions
    # =========================================================================
    "phylogenetic_dna": [
        # DNA-like (4 categories: A, C, G, T)
        {
            "name": "phylo_dna_4taxa_low_mut",
            "generator": "phylogenetic",
            "n_taxa": 4,
            "n_features": 100,
            "n_categories": 4,
            "samples_per_taxon": 25,
            "mutation_rate": 0.2,
            "root_concentration": 1.0,
            "seed": 11000,
        },
        {
            "name": "phylo_dna_8taxa_low_mut",
            "generator": "phylogenetic",
            "n_taxa": 8,
            "n_features": 200,
            "n_categories": 4,
            "samples_per_taxon": 20,
            "mutation_rate": 0.2,
            "root_concentration": 1.0,
            "seed": 11001,
        },
        {
            "name": "phylo_dna_8taxa_med_mut",
            "generator": "phylogenetic",
            "n_taxa": 8,
            "n_features": 200,
            "n_categories": 4,
            "samples_per_taxon": 20,
            "mutation_rate": 0.4,
            "root_concentration": 1.0,
            "seed": 11002,
        },
        {
            "name": "phylo_dna_16taxa_low_mut",
            "generator": "phylogenetic",
            "n_taxa": 16,
            "n_features": 500,
            "n_categories": 4,
            "samples_per_taxon": 15,
            "mutation_rate": 0.25,
            "root_concentration": 1.0,
            "seed": 11003,
        },
    ],
    "phylogenetic_protein": [
        # Protein-like (20 categories: amino acids)
        {
            "name": "phylo_protein_4taxa",
            "generator": "phylogenetic",
            "n_taxa": 4,
            "n_features": 50,
            "n_categories": 20,
            "samples_per_taxon": 30,
            "mutation_rate": 0.3,
            "root_concentration": 0.5,
            "seed": 11100,
        },
        {
            "name": "phylo_protein_8taxa",
            "generator": "phylogenetic",
            "n_taxa": 8,
            "n_features": 100,
            "n_categories": 20,
            "samples_per_taxon": 20,
            "mutation_rate": 0.35,
            "root_concentration": 0.5,
            "seed": 11101,
        },
        {
            "name": "phylo_protein_12taxa",
            "generator": "phylogenetic",
            "n_taxa": 12,
            "n_features": 150,
            "n_categories": 20,
            "samples_per_taxon": 15,
            "mutation_rate": 0.4,
            "root_concentration": 0.5,
            "seed": 11102,
        },
    ],
    "phylogenetic_divergent": [
        # High mutation rate - taxa are very divergent
        {
            "name": "phylo_divergent_4taxa",
            "generator": "phylogenetic",
            "n_taxa": 4,
            "n_features": 100,
            "n_categories": 4,
            "samples_per_taxon": 25,
            "mutation_rate": 0.7,
            "root_concentration": 1.0,
            "seed": 11200,
        },
        {
            "name": "phylo_divergent_8taxa",
            "generator": "phylogenetic",
            "n_taxa": 8,
            "n_features": 200,
            "n_categories": 4,
            "samples_per_taxon": 20,
            "mutation_rate": 0.8,
            "root_concentration": 1.0,
            "seed": 11201,
        },
    ],
    "phylogenetic_conserved": [
        # Low mutation rate - taxa are very similar (hard to distinguish)
        {
            "name": "phylo_conserved_4taxa",
            "generator": "phylogenetic",
            "n_taxa": 4,
            "n_features": 100,
            "n_categories": 4,
            "samples_per_taxon": 25,
            "mutation_rate": 0.05,
            "root_concentration": 1.0,
            "seed": 11300,
        },
        {
            "name": "phylo_conserved_8taxa",
            "generator": "phylogenetic",
            "n_taxa": 8,
            "n_features": 200,
            "n_categories": 4,
            "samples_per_taxon": 20,
            "mutation_rate": 0.08,
            "root_concentration": 1.0,
            "seed": 11301,
        },
    ],
    "phylogenetic_large": [
        # Large-scale phylogenetic simulations
        {
            "name": "phylo_large_32taxa",
            "generator": "phylogenetic",
            "n_taxa": 32,
            "n_features": 500,
            "n_categories": 4,
            "samples_per_taxon": 10,
            "mutation_rate": 0.3,
            "root_concentration": 1.0,
            "seed": 11400,
        },
        {
            "name": "phylo_large_64taxa",
            "generator": "phylogenetic",
            "n_taxa": 64,
            "n_features": 1000,
            "n_categories": 4,
            "samples_per_taxon": 8,
            "mutation_rate": 0.35,
            "root_concentration": 1.0,
            "seed": 11401,
        },
    ],
    # =========================================================================
    # TEMPORAL EVOLUTION - Growing branch simulation
    # Simulates sequence divergence along a single lineage over time
    # Adjacent time points are more similar than distant ones
    # =========================================================================
    "temporal_dna_fast": [
        # Fast evolution (high mutation rate) - easy to distinguish time points
        {
            "name": "temporal_dna_8tp_fast",
            "generator": "temporal_evolution",
            "n_time_points": 8,
            "n_features": 200,
            "n_categories": 4,
            "samples_per_time": 20,
            "mutation_rate": 0.35,
            "shift_strength": [0.2, 0.5],
            "seed": 12000,
        },
        {
            "name": "temporal_dna_10tp_fast",
            "generator": "temporal_evolution",
            "n_time_points": 10,
            "n_features": 300,
            "n_categories": 4,
            "samples_per_time": 15,
            "mutation_rate": 0.40,
            "shift_strength": [0.2, 0.5],
            "seed": 12001,
        },
        {
            "name": "temporal_dna_12tp_fast",
            "generator": "temporal_evolution",
            "n_time_points": 12,
            "n_features": 400,
            "n_categories": 4,
            "samples_per_time": 12,
            "mutation_rate": 0.35,
            "shift_strength": [0.2, 0.5],
            "seed": 12002,
        },
    ],
    "temporal_dna_moderate": [
        # Moderate evolution - some overlap between adjacent time points
        {
            "name": "temporal_dna_8tp_mod",
            "generator": "temporal_evolution",
            "n_time_points": 8,
            "n_features": 200,
            "n_categories": 4,
            "samples_per_time": 20,
            "mutation_rate": 0.20,
            "shift_strength": [0.15, 0.4],
            "seed": 12100,
        },
        {
            "name": "temporal_dna_10tp_mod",
            "generator": "temporal_evolution",
            "n_time_points": 10,
            "n_features": 300,
            "n_categories": 4,
            "samples_per_time": 15,
            "mutation_rate": 0.22,
            "shift_strength": [0.15, 0.4],
            "seed": 12101,
        },
    ],
    "temporal_dna_slow": [
        # Slow evolution (conserved) - hard to distinguish adjacent time points
        {
            "name": "temporal_dna_8tp_slow",
            "generator": "temporal_evolution",
            "n_time_points": 8,
            "n_features": 200,
            "n_categories": 4,
            "samples_per_time": 20,
            "mutation_rate": 0.10,
            "shift_strength": [0.1, 0.3],
            "seed": 12200,
        },
        {
            "name": "temporal_dna_6tp_slow",
            "generator": "temporal_evolution",
            "n_time_points": 6,
            "n_features": 300,
            "n_categories": 4,
            "samples_per_time": 25,
            "mutation_rate": 0.08,
            "shift_strength": [0.1, 0.3],
            "seed": 12201,
        },
    ],
    "temporal_protein": [
        # Protein-like evolution (20 amino acids)
        {
            "name": "temporal_protein_8tp",
            "generator": "temporal_evolution",
            "n_time_points": 8,
            "n_features": 100,
            "n_categories": 20,
            "samples_per_time": 20,
            "mutation_rate": 0.30,
            "shift_strength": [0.15, 0.4],
            "seed": 12300,
        },
        {
            "name": "temporal_protein_10tp",
            "generator": "temporal_evolution",
            "n_time_points": 10,
            "n_features": 150,
            "n_categories": 20,
            "samples_per_time": 15,
            "mutation_rate": 0.35,
            "shift_strength": [0.15, 0.4],
            "seed": 12301,
        },
    ],
    "temporal_large": [
        # Large-scale temporal simulations
        {
            "name": "temporal_large_16tp",
            "generator": "temporal_evolution",
            "n_time_points": 16,
            "n_features": 500,
            "n_categories": 4,
            "samples_per_time": 15,
            "mutation_rate": 0.30,
            "shift_strength": [0.2, 0.5],
            "seed": 12400,
        },
        {
            "name": "temporal_large_20tp",
            "generator": "temporal_evolution",
            "n_time_points": 20,
            "n_features": 800,
            "n_categories": 4,
            "samples_per_time": 12,
            "mutation_rate": 0.32,
            "shift_strength": [0.2, 0.5],
            "seed": 12401,
        },
    ],
    "temporal_highd": [
        # High-dimensional temporal evolution
        {
            "name": "temporal_highd_8tp_1k",
            "generator": "temporal_evolution",
            "n_time_points": 8,
            "n_features": 1000,
            "n_categories": 4,
            "samples_per_time": 20,
            "mutation_rate": 0.30,
            "shift_strength": [0.2, 0.5],
            "seed": 12500,
        },
        {
            "name": "temporal_highd_10tp_2k",
            "generator": "temporal_evolution",
            "n_time_points": 10,
            "n_features": 2000,
            "n_categories": 4,
            "samples_per_time": 15,
            "mutation_rate": 0.28,
            "shift_strength": [0.2, 0.5],
            "seed": 12501,
        },
    ],
}


def get_default_test_cases():
    """Flatten all test case groups into a single list."""
    return [
        case.copy() for group in DEFAULT_TEST_CASES_CONFIG.values() for case in group
    ]
