"""
Test case configurations for cluster validation.

This module contains all test case configurations organized by category.
"""

SMALL_TEST_CASES = [
    {
        "name": "clear",
        "n_samples": 24,
        "n_features": 12,
        "n_clusters": 3,
        "cluster_std": 0.4,
        "seed": 0,
    },
    {
        "name": "moderate",
        "n_samples": 30,
        "n_features": 16,
        "n_clusters": 3,
        "cluster_std": 1.0,
        "seed": 1,
    },
    {
        "name": "noisy",
        "n_samples": 30,
        "n_features": 16,
        "n_clusters": 3,
        "cluster_std": 1.6,
        "seed": 2,
    },
]

# Modular test case configuration
DEFAULT_TEST_CASES_CONFIG = {
    "gaussian_clear": [
        {
            "n_samples": 30,
            "n_features": 30,
            "n_clusters": 3,
            "cluster_std": 0.5,
            "seed": 100,
        },
        {
            "n_samples": 40,
            "n_features": 40,
            "n_clusters": 4,
            "cluster_std": 0.8,
            "seed": 101,
        },
        {
            "n_samples": 50,
            "n_features": 50,
            "n_clusters": 5,
            "cluster_std": 1.0,
            "seed": 102,
        },
    ],
    "gaussian_mixed": [
        {
            "n_samples": 35,
            "n_features": 35,
            "n_clusters": 3,
            "cluster_std": 1.2,
            "seed": 103,
        },
        {
            "n_samples": 45,
            "n_features": 45,
            "n_clusters": 4,
            "cluster_std": 1.5,
            "seed": 104,
        },
        {
            "n_samples": 55,
            "n_features": 55,
            "n_clusters": 5,
            "cluster_std": 1.8,
            "seed": 105,
        },
        {
            "n_samples": 25,
            "n_features": 25,
            "n_clusters": 2,
            "cluster_std": 0.7,
            "seed": 106,
        },
        {
            "n_samples": 65,
            "n_features": 65,
            "n_clusters": 6,
            "cluster_std": 2.0,
            "seed": 107,
        },
    ],
    "gaussian_extreme_noise": [
        {
            "n_samples": 30,
            "n_features": 30,
            "n_clusters": 3,
            "cluster_std": 5.0,
            "seed": 42,
        },
        {
            "n_samples": 40,
            "n_features": 20000,
            "n_clusters": 4,
            "cluster_std": 7.5,
            "seed": 43,
        },
        {
            "n_samples": 300,
            "n_features": 2000,
            "n_clusters": 30,
            "cluster_std": 2,
            "seed": 44,
        },
    ],
    "binary_balanced_low_entropy": [
        {
            "name": "binary_balanced_low_entropy",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 72,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_entropy",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 40,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_entropy",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 80,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_entropy",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 120,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_entropy",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 140,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_entropy",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 160,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_entropy",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 180,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_entropy",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 220,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_entropy",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 1200,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
        {
            "name": "binary_balanced_low_entropy",
            "generator": "binary",
            "n_rows": 72,
            "n_cols": 120,
            "n_clusters": 4,
            "entropy_param": 0.25,
            "balanced_clusters": True,
            "seed": 314,
        },
    ],
    "binary_unbalanced_high_entropy": [
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 36,
            "n_clusters": 4,
            "entropy_param": 0.45,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 36,
            "n_clusters": 4,
            "entropy_param": 0.12,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 300,
            "n_clusters": 4,
            "entropy_param": 0.00,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 300,
            "n_clusters": 4,
            "entropy_param": 0.01,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 300,
            "n_clusters": 4,
            "entropy_param": 0.02,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.12,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.17,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.22,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.27,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.28,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.29,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.30,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.31,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.32,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.33,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.34,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 96,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.35,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 180,
            "n_cols": 3000,
            "n_clusters": 4,
            "entropy_param": 0.35,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 360,
            "n_cols": 3000,
            "n_clusters": 8,
            "entropy_param": 0.05,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 480,
            "n_cols": 3000,
            "n_clusters": 8,
            "entropy_param": 0.10,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 480,
            "n_cols": 3000,
            "n_clusters": 12,
            "entropy_param": 0.10,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 480,
            "n_cols": 3000,
            "n_clusters": 12,
            "entropy_param": 0.15,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 480,
            "n_cols": 3000,
            "n_clusters": 12,
            "entropy_param": 0.20,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 480,
            "n_cols": 3000,
            "n_clusters": 12,
            "entropy_param": 0.25,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 480,
            "n_cols": 3000,
            "n_clusters": 8,
            "entropy_param": 0.05,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 360,
            "n_cols": 3000,
            "n_clusters": 8,
            "entropy_param": 0.10,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 360,
            "n_cols": 3000,
            "n_clusters": 12,
            "entropy_param": 0.10,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 360,
            "n_cols": 3000,
            "n_clusters": 12,
            "entropy_param": 0.15,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 360,
            "n_cols": 3000,
            "n_clusters": 12,
            "entropy_param": 0.20,
            "balanced_clusters": False,
            "seed": 2024,
        },
        {
            "name": "binary_unbalanced_high_entropy",
            "generator": "binary",
            "n_rows": 360,
            "n_cols": 3000,
            "n_clusters": 12,
            "entropy_param": 0.25,
            "balanced_clusters": False,
            "seed": 2024,
        },
    ],
}


def get_default_test_cases():
    """Flatten all test case groups into a single list."""
    return [
        case.copy() for group in DEFAULT_TEST_CASES_CONFIG.values() for case in group
    ]
